/**
 * Gen 3 species names + base stats (Phase 2.1).
 * Species 1-251 reuse Gen 2 data (same base stats for Gen 3).
 * Species 252-386 are Gen 3-native (Hoenn dex).
 * Generated by scripts/gen3_species_data.py.
 */
import { GEN2_BASE_STATS } from "../../gen2/data/baseStats";
import { GEN2_POKEMON_NAMES } from "../../gen2/data/constants";
import type { BaseStats } from "../../../interfaces";

export const GEN3_POKEMON_NAMES: string[] = [
  ...GEN2_POKEMON_NAMES, // 0-251
  "Treecko", // 252
  "Grovyle", // 253
  "Sceptile", // 254
  "Torchic", // 255
  "Combusken", // 256
  "Blaziken", // 257
  "Mudkip", // 258
  "Marshtomp", // 259
  "Swampert", // 260
  "Poochyena", // 261
  "Mightyena", // 262
  "Zigzagoon", // 263
  "Linoone", // 264
  "Wurmple", // 265
  "Silcoon", // 266
  "Beautifly", // 267
  "Cascoon", // 268
  "Dustox", // 269
  "Lotad", // 270
  "Lombre", // 271
  "Ludicolo", // 272
  "Seedot", // 273
  "Nuzleaf", // 274
  "Shiftry", // 275
  "Taillow", // 276
  "Swellow", // 277
  "Wingull", // 278
  "Pelipper", // 279
  "Ralts", // 280
  "Kirlia", // 281
  "Gardevoir", // 282
  "Surskit", // 283
  "Masquerain", // 284
  "Shroomish", // 285
  "Breloom", // 286
  "Slakoth", // 287
  "Vigoroth", // 288
  "Slaking", // 289
  "Nincada", // 290
  "Ninjask", // 291
  "Shedinja", // 292
  "Whismur", // 293
  "Loudred", // 294
  "Exploud", // 295
  "Makuhita", // 296
  "Hariyama", // 297
  "Azurill", // 298
  "Nosepass", // 299
  "Skitty", // 300
  "Delcatty", // 301
  "Sableye", // 302
  "Mawile", // 303
  "Aron", // 304
  "Lairon", // 305
  "Aggron", // 306
  "Meditite", // 307
  "Medicham", // 308
  "Electrike", // 309
  "Manectric", // 310
  "Plusle", // 311
  "Minun", // 312
  "Volbeat", // 313
  "Illumise", // 314
  "Roselia", // 315
  "Gulpin", // 316
  "Swalot", // 317
  "Carvanha", // 318
  "Sharpedo", // 319
  "Wailmer", // 320
  "Wailord", // 321
  "Numel", // 322
  "Camerupt", // 323
  "Torkoal", // 324
  "Spoink", // 325
  "Grumpig", // 326
  "Spinda", // 327
  "Trapinch", // 328
  "Vibrava", // 329
  "Flygon", // 330
  "Cacnea", // 331
  "Cacturne", // 332
  "Swablu", // 333
  "Altaria", // 334
  "Zangoose", // 335
  "Seviper", // 336
  "Lunatone", // 337
  "Solrock", // 338
  "Barboach", // 339
  "Whiscash", // 340
  "Corphish", // 341
  "Crawdaunt", // 342
  "Baltoy", // 343
  "Claydol", // 344
  "Lileep", // 345
  "Cradily", // 346
  "Anorith", // 347
  "Armaldo", // 348
  "Feebas", // 349
  "Milotic", // 350
  "Castform", // 351
  "Kecleon", // 352
  "Shuppet", // 353
  "Banette", // 354
  "Duskull", // 355
  "Dusclops", // 356
  "Tropius", // 357
  "Chimecho", // 358
  "Absol", // 359
  "Wynaut", // 360
  "Snorunt", // 361
  "Glalie", // 362
  "Spheal", // 363
  "Sealeo", // 364
  "Walrein", // 365
  "Clamperl", // 366
  "Huntail", // 367
  "Gorebyss", // 368
  "Relicanth", // 369
  "Luvdisc", // 370
  "Bagon", // 371
  "Shelgon", // 372
  "Salamence", // 373
  "Beldum", // 374
  "Metang", // 375
  "Metagross", // 376
  "Regirock", // 377
  "Regice", // 378
  "Registeel", // 379
  "Latias", // 380
  "Latios", // 381
  "Kyogre", // 382
  "Groudon", // 383
  "Rayquaza", // 384
  "Jirachi", // 385
  "Deoxys", // 386
];

export const GEN3_BASE_STATS: Record<number, BaseStats> = {
  ...GEN2_BASE_STATS, // 1-251

  252: { hp: 40, attack: 45, defense: 35, speed: 70, spAtk: 50, spDef: 50 }, // Treecko
  253: { hp: 50, attack: 65, defense: 45, speed: 95, spAtk: 85, spDef: 65 }, // Grovyle
  254: { hp: 70, attack: 85, defense: 65, speed: 120, spAtk: 105, spDef: 85 }, // Sceptile
  255: { hp: 45, attack: 60, defense: 40, speed: 45, spAtk: 70, spDef: 50 }, // Torchic
  256: { hp: 60, attack: 85, defense: 60, speed: 55, spAtk: 85, spDef: 60 }, // Combusken
  257: { hp: 80, attack: 120, defense: 70, speed: 80, spAtk: 110, spDef: 70 }, // Blaziken
  258: { hp: 50, attack: 70, defense: 50, speed: 40, spAtk: 50, spDef: 50 }, // Mudkip
  259: { hp: 70, attack: 85, defense: 70, speed: 50, spAtk: 60, spDef: 70 }, // Marshtomp
  260: { hp: 100, attack: 110, defense: 90, speed: 60, spAtk: 95, spDef: 90 }, // Swampert
  261: { hp: 35, attack: 55, defense: 35, speed: 35, spAtk: 30, spDef: 30 }, // Poochyena
  262: { hp: 70, attack: 90, defense: 70, speed: 70, spAtk: 60, spDef: 60 }, // Mightyena
  263: { hp: 38, attack: 30, defense: 41, speed: 60, spAtk: 30, spDef: 41 }, // Zigzagoon
  264: { hp: 78, attack: 70, defense: 61, speed: 100, spAtk: 50, spDef: 61 }, // Linoone
  265: { hp: 45, attack: 45, defense: 35, speed: 20, spAtk: 20, spDef: 30 }, // Wurmple
  266: { hp: 50, attack: 35, defense: 55, speed: 15, spAtk: 25, spDef: 25 }, // Silcoon
  267: { hp: 60, attack: 70, defense: 50, speed: 65, spAtk: 100, spDef: 50 }, // Beautifly
  268: { hp: 50, attack: 35, defense: 55, speed: 15, spAtk: 25, spDef: 25 }, // Cascoon
  269: { hp: 60, attack: 50, defense: 70, speed: 65, spAtk: 50, spDef: 90 }, // Dustox
  270: { hp: 40, attack: 30, defense: 30, speed: 30, spAtk: 40, spDef: 50 }, // Lotad
  271: { hp: 60, attack: 50, defense: 50, speed: 50, spAtk: 60, spDef: 70 }, // Lombre
  272: { hp: 80, attack: 70, defense: 70, speed: 70, spAtk: 90, spDef: 100 }, // Ludicolo
  273: { hp: 40, attack: 40, defense: 50, speed: 30, spAtk: 30, spDef: 30 }, // Seedot
  274: { hp: 70, attack: 70, defense: 40, speed: 60, spAtk: 60, spDef: 40 }, // Nuzleaf
  275: { hp: 90, attack: 100, defense: 60, speed: 80, spAtk: 90, spDef: 60 }, // Shiftry
  276: { hp: 40, attack: 55, defense: 30, speed: 85, spAtk: 30, spDef: 30 }, // Taillow
  277: { hp: 60, attack: 85, defense: 60, speed: 125, spAtk: 50, spDef: 50 }, // Swellow
  278: { hp: 40, attack: 30, defense: 30, speed: 85, spAtk: 55, spDef: 30 }, // Wingull
  279: { hp: 60, attack: 50, defense: 100, speed: 65, spAtk: 95, spDef: 70 }, // Pelipper
  280: { hp: 28, attack: 25, defense: 25, speed: 40, spAtk: 45, spDef: 35 }, // Ralts
  281: { hp: 38, attack: 35, defense: 35, speed: 50, spAtk: 65, spDef: 55 }, // Kirlia
  282: { hp: 68, attack: 65, defense: 65, speed: 80, spAtk: 125, spDef: 115 }, // Gardevoir
  283: { hp: 40, attack: 30, defense: 32, speed: 65, spAtk: 50, spDef: 52 }, // Surskit
  284: { hp: 70, attack: 60, defense: 62, speed: 80, spAtk: 100, spDef: 82 }, // Masquerain
  285: { hp: 60, attack: 40, defense: 60, speed: 35, spAtk: 40, spDef: 60 }, // Shroomish
  286: { hp: 60, attack: 130, defense: 80, speed: 70, spAtk: 60, spDef: 60 }, // Breloom
  287: { hp: 60, attack: 60, defense: 60, speed: 30, spAtk: 35, spDef: 35 }, // Slakoth
  288: { hp: 80, attack: 80, defense: 80, speed: 90, spAtk: 55, spDef: 55 }, // Vigoroth
  289: { hp: 150, attack: 160, defense: 100, speed: 100, spAtk: 95, spDef: 65 }, // Slaking
  290: { hp: 31, attack: 45, defense: 90, speed: 40, spAtk: 30, spDef: 30 }, // Nincada
  291: { hp: 61, attack: 90, defense: 45, speed: 160, spAtk: 50, spDef: 50 }, // Ninjask
  292: { hp: 1, attack: 90, defense: 45, speed: 40, spAtk: 30, spDef: 30 }, // Shedinja
  293: { hp: 64, attack: 51, defense: 23, speed: 28, spAtk: 51, spDef: 23 }, // Whismur
  294: { hp: 84, attack: 71, defense: 43, speed: 48, spAtk: 71, spDef: 43 }, // Loudred
  295: { hp: 104, attack: 91, defense: 63, speed: 68, spAtk: 91, spDef: 73 }, // Exploud
  296: { hp: 72, attack: 60, defense: 30, speed: 25, spAtk: 20, spDef: 30 }, // Makuhita
  297: { hp: 144, attack: 120, defense: 60, speed: 50, spAtk: 40, spDef: 60 }, // Hariyama
  298: { hp: 50, attack: 20, defense: 40, speed: 20, spAtk: 20, spDef: 40 }, // Azurill
  299: { hp: 30, attack: 45, defense: 135, speed: 30, spAtk: 45, spDef: 90 }, // Nosepass
  300: { hp: 50, attack: 45, defense: 45, speed: 50, spAtk: 35, spDef: 35 }, // Skitty
  301: { hp: 70, attack: 65, defense: 65, speed: 70, spAtk: 55, spDef: 55 }, // Delcatty
  302: { hp: 50, attack: 75, defense: 75, speed: 50, spAtk: 65, spDef: 65 }, // Sableye
  303: { hp: 50, attack: 85, defense: 85, speed: 50, spAtk: 55, spDef: 55 }, // Mawile
  304: { hp: 50, attack: 70, defense: 100, speed: 50, spAtk: 40, spDef: 40 }, // Aron
  305: { hp: 60, attack: 90, defense: 140, speed: 40, spAtk: 50, spDef: 50 }, // Lairon
  306: { hp: 70, attack: 110, defense: 180, speed: 50, spAtk: 60, spDef: 60 }, // Aggron
  307: { hp: 30, attack: 40, defense: 55, speed: 60, spAtk: 40, spDef: 55 }, // Meditite
  308: { hp: 60, attack: 60, defense: 75, speed: 80, spAtk: 60, spDef: 75 }, // Medicham
  309: { hp: 40, attack: 45, defense: 40, speed: 65, spAtk: 65, spDef: 40 }, // Electrike
  310: { hp: 70, attack: 75, defense: 60, speed: 105, spAtk: 105, spDef: 60 }, // Manectric
  311: { hp: 60, attack: 50, defense: 40, speed: 95, spAtk: 85, spDef: 75 }, // Plusle
  312: { hp: 60, attack: 40, defense: 50, speed: 95, spAtk: 75, spDef: 85 }, // Minun
  313: { hp: 65, attack: 73, defense: 75, speed: 85, spAtk: 47, spDef: 85 }, // Volbeat
  314: { hp: 65, attack: 47, defense: 75, speed: 85, spAtk: 73, spDef: 85 }, // Illumise
  315: { hp: 50, attack: 60, defense: 45, speed: 65, spAtk: 100, spDef: 80 }, // Roselia
  316: { hp: 70, attack: 43, defense: 53, speed: 40, spAtk: 43, spDef: 53 }, // Gulpin
  317: { hp: 100, attack: 73, defense: 83, speed: 55, spAtk: 73, spDef: 83 }, // Swalot
  318: { hp: 45, attack: 90, defense: 20, speed: 65, spAtk: 65, spDef: 20 }, // Carvanha
  319: { hp: 70, attack: 120, defense: 40, speed: 95, spAtk: 95, spDef: 40 }, // Sharpedo
  320: { hp: 130, attack: 70, defense: 35, speed: 60, spAtk: 70, spDef: 35 }, // Wailmer
  321: { hp: 170, attack: 90, defense: 45, speed: 60, spAtk: 90, spDef: 45 }, // Wailord
  322: { hp: 60, attack: 60, defense: 40, speed: 35, spAtk: 65, spDef: 40 }, // Numel
  323: { hp: 70, attack: 100, defense: 70, speed: 40, spAtk: 105, spDef: 75 }, // Camerupt
  324: { hp: 70, attack: 85, defense: 140, speed: 20, spAtk: 85, spDef: 70 }, // Torkoal
  325: { hp: 60, attack: 25, defense: 35, speed: 60, spAtk: 70, spDef: 80 }, // Spoink
  326: { hp: 80, attack: 45, defense: 65, speed: 80, spAtk: 90, spDef: 110 }, // Grumpig
  327: { hp: 60, attack: 60, defense: 60, speed: 60, spAtk: 60, spDef: 60 }, // Spinda
  328: { hp: 45, attack: 100, defense: 45, speed: 10, spAtk: 45, spDef: 45 }, // Trapinch
  329: { hp: 50, attack: 70, defense: 50, speed: 70, spAtk: 50, spDef: 50 }, // Vibrava
  330: { hp: 80, attack: 100, defense: 80, speed: 100, spAtk: 80, spDef: 80 }, // Flygon
  331: { hp: 50, attack: 85, defense: 40, speed: 35, spAtk: 85, spDef: 40 }, // Cacnea
  332: { hp: 70, attack: 115, defense: 60, speed: 55, spAtk: 115, spDef: 60 }, // Cacturne
  333: { hp: 45, attack: 40, defense: 60, speed: 50, spAtk: 40, spDef: 75 }, // Swablu
  334: { hp: 75, attack: 70, defense: 90, speed: 80, spAtk: 70, spDef: 105 }, // Altaria
  335: { hp: 73, attack: 115, defense: 60, speed: 90, spAtk: 60, spDef: 60 }, // Zangoose
  336: { hp: 73, attack: 100, defense: 60, speed: 65, spAtk: 100, spDef: 60 }, // Seviper
  337: { hp: 70, attack: 55, defense: 65, speed: 70, spAtk: 95, spDef: 85 }, // Lunatone
  338: { hp: 70, attack: 95, defense: 85, speed: 70, spAtk: 55, spDef: 65 }, // Solrock
  339: { hp: 50, attack: 48, defense: 43, speed: 60, spAtk: 46, spDef: 41 }, // Barboach
  340: { hp: 110, attack: 78, defense: 73, speed: 60, spAtk: 76, spDef: 71 }, // Whiscash
  341: { hp: 43, attack: 80, defense: 65, speed: 35, spAtk: 50, spDef: 35 }, // Corphish
  342: { hp: 63, attack: 120, defense: 85, speed: 55, spAtk: 90, spDef: 55 }, // Crawdaunt
  343: { hp: 40, attack: 40, defense: 55, speed: 40, spAtk: 40, spDef: 70 }, // Baltoy
  344: { hp: 60, attack: 70, defense: 105, speed: 75, spAtk: 70, spDef: 120 }, // Claydol
  345: { hp: 66, attack: 41, defense: 77, speed: 23, spAtk: 61, spDef: 87 }, // Lileep
  346: { hp: 86, attack: 81, defense: 97, speed: 43, spAtk: 81, spDef: 107 }, // Cradily
  347: { hp: 45, attack: 95, defense: 50, speed: 75, spAtk: 40, spDef: 50 }, // Anorith
  348: { hp: 75, attack: 125, defense: 100, speed: 45, spAtk: 70, spDef: 80 }, // Armaldo
  349: { hp: 20, attack: 15, defense: 20, speed: 80, spAtk: 10, spDef: 55 }, // Feebas
  350: { hp: 95, attack: 60, defense: 79, speed: 81, spAtk: 100, spDef: 125 }, // Milotic
  351: { hp: 70, attack: 70, defense: 70, speed: 70, spAtk: 70, spDef: 70 }, // Castform
  352: { hp: 60, attack: 90, defense: 70, speed: 40, spAtk: 60, spDef: 120 }, // Kecleon
  353: { hp: 44, attack: 75, defense: 35, speed: 45, spAtk: 63, spDef: 33 }, // Shuppet
  354: { hp: 64, attack: 115, defense: 65, speed: 65, spAtk: 83, spDef: 63 }, // Banette
  355: { hp: 20, attack: 40, defense: 90, speed: 25, spAtk: 30, spDef: 90 }, // Duskull
  356: { hp: 40, attack: 70, defense: 130, speed: 25, spAtk: 60, spDef: 130 }, // Dusclops
  357: { hp: 99, attack: 68, defense: 83, speed: 51, spAtk: 72, spDef: 87 }, // Tropius
  358: { hp: 65, attack: 50, defense: 70, speed: 65, spAtk: 95, spDef: 80 }, // Chimecho
  359: { hp: 65, attack: 130, defense: 60, speed: 75, spAtk: 75, spDef: 60 }, // Absol
  360: { hp: 95, attack: 23, defense: 48, speed: 23, spAtk: 23, spDef: 48 }, // Wynaut
  361: { hp: 50, attack: 50, defense: 50, speed: 50, spAtk: 50, spDef: 50 }, // Snorunt
  362: { hp: 80, attack: 80, defense: 80, speed: 80, spAtk: 80, spDef: 80 }, // Glalie
  363: { hp: 70, attack: 40, defense: 50, speed: 25, spAtk: 55, spDef: 50 }, // Spheal
  364: { hp: 90, attack: 60, defense: 70, speed: 45, spAtk: 75, spDef: 70 }, // Sealeo
  365: { hp: 110, attack: 80, defense: 90, speed: 65, spAtk: 95, spDef: 90 }, // Walrein
  366: { hp: 35, attack: 64, defense: 85, speed: 32, spAtk: 74, spDef: 55 }, // Clamperl
  367: { hp: 55, attack: 104, defense: 105, speed: 52, spAtk: 94, spDef: 75 }, // Huntail
  368: { hp: 55, attack: 84, defense: 105, speed: 52, spAtk: 114, spDef: 75 }, // Gorebyss
  369: { hp: 100, attack: 90, defense: 130, speed: 55, spAtk: 45, spDef: 65 }, // Relicanth
  370: { hp: 43, attack: 30, defense: 55, speed: 97, spAtk: 40, spDef: 65 }, // Luvdisc
  371: { hp: 45, attack: 75, defense: 60, speed: 50, spAtk: 40, spDef: 30 }, // Bagon
  372: { hp: 65, attack: 95, defense: 100, speed: 50, spAtk: 60, spDef: 50 }, // Shelgon
  373: { hp: 95, attack: 135, defense: 80, speed: 100, spAtk: 110, spDef: 80 }, // Salamence
  374: { hp: 40, attack: 55, defense: 80, speed: 30, spAtk: 35, spDef: 60 }, // Beldum
  375: { hp: 60, attack: 75, defense: 100, speed: 50, spAtk: 55, spDef: 80 }, // Metang
  376: { hp: 80, attack: 95, defense: 130, speed: 70, spAtk: 95, spDef: 90 }, // Metagross
  377: { hp: 80, attack: 100, defense: 200, speed: 50, spAtk: 50, spDef: 100 }, // Regirock
  378: { hp: 80, attack: 50, defense: 100, speed: 50, spAtk: 100, spDef: 200 }, // Regice
  379: { hp: 80, attack: 75, defense: 150, speed: 50, spAtk: 75, spDef: 150 }, // Registeel
  380: { hp: 80, attack: 80, defense: 90, speed: 110, spAtk: 110, spDef: 130 }, // Latias
  381: { hp: 80, attack: 90, defense: 80, speed: 110, spAtk: 130, spDef: 110 }, // Latios
  382: { hp: 100, attack: 100, defense: 90, speed: 90, spAtk: 150, spDef: 140 }, // Kyogre
  383: { hp: 100, attack: 150, defense: 140, speed: 90, spAtk: 100, spDef: 90 }, // Groudon
  384: { hp: 105, attack: 150, defense: 90, speed: 95, spAtk: 150, spDef: 90 }, // Rayquaza
  385: { hp: 100, attack: 100, defense: 100, speed: 100, spAtk: 100, spDef: 100 }, // Jirachi
  386: { hp: 50, attack: 150, defense: 50, speed: 150, spAtk: 150, spDef: 50 }, // Deoxys
};

export function getGen3BaseStats(dexId: number): BaseStats | undefined {
  return GEN3_BASE_STATS[dexId];
}
